openapi: 3.0.0
info:
  title: Financial Advisor core
  version: 1.0.0
paths:
  /users/login:
  post:
    summary: login api
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              userName:
                type: string
              password:
                type: string
            required:
              - userName
              - password
    responses:
      '200':
        description: Successful retrieval
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                data:
                  type: array
                  items:
                    type: object
      '400':
        description: Bad request
        content:
          application/json:
            schema:
              type: object
              properties:
                error:
                  type: string
                message:
                  type: string
