openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for user management including login functionality.

paths:
  /users/login:
    post:
      summary: User Login
      description: Authenticates a user and returns a token if successful.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                  example: "test@example.com"
                password:
                  type: string
                  description: The password for the user account.
                  example: "your_password"
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: The JWT token returned upon successful authentication.
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                        description: The username of the logged-in user.
                        example: "test@example.com"
        '401':
          description: Unauthorized - Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid username or password."
        '400':
          description: Bad Request - Missing parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Username and password are required."
